import React from "react";
import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";
import Navbar from "../../components/Navbar";
import DrinkDetail from "../../components/DrinkDetail";
import { useRouter } from "next/router";

const detail = () => {
  const [drink, setDrink] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    if (router.isReady) {
      const fetchDrink = async () => {
        setLoading(true);
        try {
          const res = await axios.get(`https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=${id}`);
          setDrink(res.data.drinks);
          console.log(res.data.drinks);
          setLoading(false);
        } catch (error) {
          console.error(error);
          setError(true);
          setLoading(false);
        }
      };
      fetchDrink();
    }
  }, [router.isReady]);

  return (
    <div className="">
      <Head>
        <title>Cocktails Menu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cocktails.png" />
      </Head>

      <Navbar />
      <main>
        {loading && <div className="w-16 h-16 mx-auto mt-64 border-8 border-green-600 border-solid rounded-full animate-spin border-t-white"></div>}
        {error && <p>Oopss...</p>}
        {drink?.length > 0 && <DrinkDetail drinksData={drink} />}
      </main>
    </div>
  );
};

export default detail;
