import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";

import Navbar from "../../components/Navbar";
import Drinks from "../../components/Drinks";

export default function Cocktail() {
  const [cocktailsName, setCocktailsName] = useState("");
  const [drink, setDrink] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);

  useEffect(() => {
    const fetchDrink = async () => {
      setLoading(true);
      try {
        const res = await axios.get(`https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${cocktailsName}`);
        console.log(res.data);
        setDrink(res.data.drinks);
        setLoading(false);
      } catch (error) {
        console.error(error);
        setError(true);
        setLoading(false);
      }
    };
    fetchDrink();
  }, [cocktailsName]);

  const handleChange = (e) => {
    setCocktailsName(e.target.value);
  };

  return (
    <div className="bg-green-800">
      <Head>
        <title>Drinks Menu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cocktails.png" />
      </Head>

      <Navbar />

      <input
        type="text"
        name="cocktails"
        onChange={handleChange}
        placeholder="Search Cocktails you want..."
        className="w-3/6 md:w-2/3 lg:w-10/12 block px-4 py-3 mt-8 mx-auto text-base border border-green-600 rounded outline-none  focus:ring-green-600 focus:border-blue-500 focus:ring-1"
      />
      <main className="bg-green-800">
        {loading && <div className="w-16 h-16 mx-auto mt-64 border-8 border-blue-400 border-solid rounded-full animate-spin border-t-white"></div>}
        {error && <p>Oopss...</p>}
        {drink !== null ? <Drinks drinksData={drink} /> : "There is no result for keyword, please try another keyword!"}
      </main>

      <footer className="bg-green-600">
        <p className="font-semibold py-8 text-xl text-white text-center">Made Using Next JS By Wildan</p>
      </footer>
    </div>
  );
}
