import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import axios from "axios";
import Navbar from "../components/Navbar";
import Drinks from "../components/Drinks";

export default function Home() {
  const [drink, setDrink] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);

  useEffect(() => {
    const fetchDrink = async () => {
      setLoading(true);
      try {
        const res = await axios.get(`https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a`);
        setDrink(res.data.drinks);
        setLoading(false);
      } catch (error) {
        console.error(error);
        setError(true);
        setLoading(false);
      }
    };
    fetchDrink();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Cocktails Menu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cocktails.png" />
      </Head>

      <Navbar />

      <main>
        {loading && <div className="w-16 h-16 border-8 border-blue-400 border-solid rounded-full animate-spin border-t-white"></div>}
        {error && <p>Oopss...</p>}
        {drink.length > 0 && <Drinks drinksData={drink} />}
      </main>

      <footer className="">
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
